# Generated by Django 5.2.1 on 2025-09-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('occupation', models.CharField(default='', max_length=50)),
                ('charge_per_hr', models.IntegerField(default=0)),
                ('ratings', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
