# Generated by Django 5.2.1 on 2025-09-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='on_work',
            field=models.BooleanField(default=False),
        ),
    ]
