# Generated by Django 5.2.1 on 2025-09-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_workers_on_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='work_done',
            field=models.BooleanField(default=True),
        ),
    ]
