# Generated by Django 5.2.1 on 2025-09-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_workers_work_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
