# Generated by Django 5.2.1 on 2025-09-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='history',
            field=models.ManyToManyField(blank=True, to='mainapp.workers'),
        ),
    ]
