# Generated by Django 5.2.1 on 2025-09-16 07:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_user_profile_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='history',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
